import type { GraphEdge, GraphNode, Problem } from './types.js';

/**
 * Place the nodes, left to right, without being told where anything goes.
 *
 * Positions are derived rather than stored, which is the point: a
 * `processing.json` written by hand, or generated by a build script, opens as a
 * readable picture straight away. Nothing has to be migrated, and two people
 * editing the same config never fight over coordinates.
 *
 * Depth is the longest path from the raw frame, so a node always sits to the
 * right of everything it reads. Lanes are then ordered by the average position
 * of each node's inputs, which is the standard cheap way to keep edges short
 * and mostly untangled.
 */
export function layout(
  nodes: GraphNode[],
  edges: GraphEdge[],
  problems: Problem[],
): { nodes: GraphNode[]; depth: number; lanes: number } {
  const byId = new Map(nodes.map((n) => [n.id, n]));

  // ---- depth: longest path, with cycles reported rather than followed -------
  const depth = new Map<string, number>();
  const visiting = new Set<string>();
  const reported = new Set<string>();

  const depthOf = (id: string, path: string[]): number => {
    const known = depth.get(id);
    if (known !== undefined) return known;

    if (visiting.has(id)) {
      const cycle = [...path.slice(path.indexOf(id)), id].join(' -> ');
      if (!reported.has(cycle)) {
        reported.add(cycle);
        problems.push({
          severity: 'error',
          code: 'cycle',
          node: id,
          message: `"${id}" is part of a cycle: ${cycle}`,
        });
      }
      // Break it here so the rest of the graph still lays out and can be drawn.
      return 0;
    }

    visiting.add(id);
    const node = byId.get(id);
    const value = !node?.requires.length
      ? 0
      : Math.max(...node.requires.map((req) => depthOf(req, [...path, id]) + 1));
    visiting.delete(id);

    depth.set(id, value);
    return value;
  };

  for (const node of nodes) node.depth = depthOf(node.id, []);

  // ---- lanes: one pass of barycentre ordering per column -------------------
  const columns = new Map<number, GraphNode[]>();
  for (const node of nodes) {
    if (!columns.has(node.depth)) columns.set(node.depth, []);
    columns.get(node.depth)!.push(node);
  }

  const lanes = new Map<string, number>();
  let widest = 0;

  for (const column of [...columns.keys()].sort((a, b) => a - b)) {
    const members = columns.get(column)!;
    const weight = (node: GraphNode): number => {
      const parents = node.requires.map((r) => lanes.get(r)).filter((v): v is number => v !== undefined);
      // Nothing upstream to follow: sort by name, so the result is stable.
      return parents.length ? parents.reduce((a, b) => a + b, 0) / parents.length : Number.POSITIVE_INFINITY;
    };
    members.sort((a, b) => weight(a) - weight(b) || a.id.localeCompare(b.id));
    members.forEach((node, i) => {
      node.lane = i;
      lanes.set(node.id, i);
    });
    widest = Math.max(widest, members.length);
  }

  return {
    nodes,
    depth: columns.size ? Math.max(...columns.keys()) + 1 : 0,
    lanes: widest,
  };
}
